language: python
python:
- '3.3'
- '3.4'
- '3.5'
install:
- python setup.py -q install
script:
- nosetests
deploy:
  provider: pypi
  user: Gohla
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: Gohla/bintraypy_cli
